name: Build and Deploy Docker Image
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - 'docker-compose.yml'
      - 'license.txt'
      - 'readme.md'
jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: true
    steps:
      - 
        id: checkout
        uses: actions/checkout@v4
      - 
        id: setup-qemu
        uses: docker/setup-qemu-action@v3
      - 
        id: setup-docker-buildx
        uses: docker/setup-buildx-action@v3
      -
        id: docker-buildx
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: iamryusei/dynu-on-docker:latest
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          load: true
          push: false
      - 
        id: docker-login-ghcr
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - 
        id: docker-push
        run: |-
          docker tag iamryusei/dynu-on-docker:latest ghcr.io/iamryusei/dynu-on-docker:latest
          docker push ghcr.io/iamryusei/dynu-on-docker:latest
